### ISSUE TITLE
Can't install birt-controls-lib: Eclipse update site not available?!

### ISSUE THREAD

**Issue by luisgois** [innoventsolutions/birt-controls-lib#20]
Eclipse can't find the controls in the update site referred in your installation page. Is it still available?

**Comment by yesmanny** [comment]
Same problem here. Update site isn't available. How can I install the controls plugin in eclipse?

**Comment by SteveSchafer-Innovent** [comment]
Works for me.  Tried in eclipse-neon, eclipse-photon, and eclipse-2018-12.
