### ISSUE TITLE
Rotate text in BIRT

### ISSUE THREAD

**Issue by shravaliraju** [innoventsolutions/birt-controls-lib#21]
Unable to download the eclipse BIRT rotate text plugins for the new version. Is there any way to point?

**Comment by SteveSchafer-Innovent** [comment]
I was able to run the rotated text plugin in eclipse 4.8 (which uses BIRT 4.7).   I then built the jar with eclipse export to plugin and copied it to WEB-INF/lib in a tomcat installation of BIRT 4.8 viewer and it worked there too.  I didn't change any of the code.
