### ISSUE TITLE
RotatedText with low resolution

### ISSUE THREAD

**Issue by GoogleCodeExporter** [innoventsolutions/birt-controls-lib#9]
```
Hello,

We are using the rotatedText and we observe that the text appear in very low 
resolution at previewing report in pdf.

Thanks


```

Original issue reported on code.google.com by `rogerlop...@gmail.com` on 6 Apr 2011 at 8:23

**Comment by SteveSchafer-Innovent** [comment]
We are at the mercy of how java awt renders fonts in an image.  It is beyond the current scope to fix this so closing for now.
